name: run tests and generate report

on:
  workflow_dispatch:
    inputs:
      context:
        type: choice
        description: Select the environment
        default: staging
        options:
        - staging
      browser:
        type: choice
        description: Select the browser
        default: 'chrome'
        options:
        - chrome
        - electron
      type:
        type: choice
        description: Selec the test suite
        options:
          - full-regression
          - smoke
          - post-release


jobs:
  test:
    environment: ${{inputs.context}}
    name: Cypress run
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: read
      pages: read
      checks: write
    container: cypress/browsers:node-16.18.1-chrome-109.0.5414.74-1-ff-109.0-edge-109.0.1518.52-1
    steps:
      - uses: actions/checkout@v3

      - name: Setting container permissions for cypress
        run: |
          mkdir /root/.cache
          chmod 777 -R /root/.cache
          chmod 777 -R cypress/

      - name: NPM INSTALL
        run: npm i

      - name: Cypress run
        if: always()
        uses: cypress-io/github-action@v5
        with:
          command: |
            npx cypress run --browser ${{inputs.browser}}

      - name: Get Allure history
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: history-${{inputs.context}}-${{inputs.type}}
          path: gh-pages
          #ref: gh-pages
          #path: ${{inputs.context}}/${{inputs.type}}

#      - name: Move Results
#        run: |
#          mkdir -p allure/allure-results
#          cp -r allure-results/. allure/allure-results/

      - name: Generate Allure Report
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_report: allure-report
          allure_results: allure-results
          allure_history: allure-history
          #allure_report: allure/allure-report
          #allure_results: allure/allure-results
          #allure_history: allure/allure-history/${{inputs.context}}/${{inputs.type}}
          #github_repo: blckfalcon/cypress-allure-actions/${{inputs.context}}/${{inputs.type}}
          keep_reports: 2

      - name: List files in the repository
        run: |
            ls

      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          #BRANCH: gh-pages
          #FOLDER: ${{inputs.context}}/${{inputs.type}}
          BRANCH: history-${{inputs.context}}-${{inputs.type}}
          FOLDER: allure-history
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#      - name: List files in the repository
#        run: |
#            ls allure-history/
#            echo "lul"
#            ls staging-full-regression/

#      - name: Create a publish directory for publication
#        run: |
#          mkdir -p publish/${{inputs.context}}/${{inputs.type}}
#          cp -r allure/allure-history/${{inputs.context}}/${{inputs.type}}/. ./publish/${{inputs.context}}/${{inputs.type}}/
#          cp ./.github/workflows/generate-report-template.html ./publish/index.html

      - name: Create a publish directory for publication
        run: |
          mkdir -p publish/
          cp -r allure-history/. ./publish/${{inputs.context}}-${{inputs.type}}/
          cp ./.github/workflows/generate-report-template.html ./publish/index.html

      - uses: actions/checkout@v3
        if: inputs.context == 'staging' && inputs.type == 'full-regression'
        continue-on-error: true
        with:
          ref: history-${{inputs.context}}-${{inputs.type}}
          path: publish/staging-full-regression
      - uses: actions/checkout@v3
        if: inputs.context == 'staging' && inputs.type == 'smoke'
        continue-on-error: true
        with:
          ref: history-${{inputs.context}}-${{inputs.type}}
          path: publish/staging-smoke
      - uses: actions/checkout@v3
        if: inputs.context == 'staging' && inputs.type == 'post-release'
        continue-on-error: true
        with:
          ref: history-${{inputs.context}}-${{inputs.type}}
          path: publish/staging-post-release

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: publish
          keep_files: true

